@host=https://localhost:7148

GET {{host}}/schueler/getallschueler
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNWQ3ZmEzMy1mYjM4LTQ3NmItOTI0NC05ZTQ4ZjFmYjQ3NDYiLCJnaXZlbl9uYW1lIjoiRG9taW5payIsImZhbWlseV9uYW1lIjoiU2Nob2VuaGVpdCIsImp0aSI6IjU4NmU5ODRhLTYxMDItNDIzZS1iOGM4LWNiZjQxZjFmZWY5MiIsImV4cCI6MTY5OTI4NDM2OSwiaXNzIjoiQlRfRFNfRmFocnNjaHVsZSIsImF1ZCI6IkJUX0RTX0ZhaHJzY2h1bGUifQ.0di-VL8KjfU3XljehttK8h_lxlXJLCriqNeqeMXqd04